import Head from 'next/head';
import GlobalContext from '../context';
import '../styles/globals.scss';

function MyApp({ Component, pageProps }) {
  return (
    <GlobalContext>
      <Head>
        <title>Calculadora de Investimentos</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Component {...pageProps} />
    </GlobalContext>
  );
}

export default MyApp;
