import { useContext } from 'react';
import Head from 'next/head'
import Simulador from '../components/Simulador';
import ResultadoDaSimulacao from '../components/ResultadoDaSimulacao';
import { Info } from '../context/info';
import styles from '../styles/Home.module.scss';

export default function Home() {
  const context = useContext(Info);

  return (
    <div className={styles.container}>
      <Head>
        <title>Calculadora de Investimentos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.content}>
        <header>
          <h1>Simulador de Investimentos</h1>
        </header>
        
        <section>
          <Simulador />
          <ResultadoDaSimulacao />
        </section>
      </main>
    </div>
  )
}
